# Declara el contrato SQL y de materialización de dbo.tiempos_mlp.
from ada.processes.dispatch.catalog.columns import column
from ada.processes.dispatch.models import (
    DispatchLoadStrategy,
    DispatchSourceDefinition,
    DispatchStorageMode,
    DispatchValueKind,
)

DEFINITION = DispatchSourceDefinition(
    source_key='tiempos_mlp',
    source_table='dbo.tiempos_mlp',
    enabled=True,
    storage_mode=DispatchStorageMode.SHIFT,
    load_strategy=DispatchLoadStrategy.SHIFT_WINDOW,
    shift_id_column='ShiftId',
    source_last_update_output_column='moment',
    columns=(
        column(
            source_name='Id',
            output_name='id',
            value_kind=DispatchValueKind.INTEGER,
            required=True,
        ),
        column(
            source_name='ShiftId',
            output_name='shift_id',
            value_kind=DispatchValueKind.INTEGER,
            required=True,
        ),
        column(
            source_name='Equipment',
            output_name='equipment',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='Eqmttype',
            output_name='eqmttype',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='Unit',
            output_name='unit',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='Crew',
            output_name='crew',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='ShiftStartDate',
            output_name='shift_start_date',
            value_kind=DispatchValueKind.DATETIME,
            required=False,
        ),
        column(
            source_name='ShiftStartDateTime',
            output_name='shift_start_date_time',
            value_kind=DispatchValueKind.DATETIME,
            required=False,
        ),
        column(
            source_name='FullShiftSuffix',
            output_name='full_shift_suffix',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='FullShiftName',
            output_name='full_shift_name',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='shiftdate',
            output_name='shiftdate',
            value_kind=DispatchValueKind.DATE,
            required=False,
        ),
        column(
            source_name='Operator',
            output_name='operator',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='OperId',
            output_name='oper_id',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='logintime',
            output_name='logintime',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='CategoryIdx',
            output_name='category_idx',
            value_kind=DispatchValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='Category',
            output_name='category',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='Reason',
            output_name='reason',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='Code',
            output_name='code',
            value_kind=DispatchValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='Comments',
            output_name='comments',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='Duration',
            output_name='duration',
            value_kind=DispatchValueKind.INTEGER,
            required=False,
        ),
        column(
            source_name='Status',
            output_name='status',
            value_kind=DispatchValueKind.TEXT,
            required=False,
        ),
        column(
            source_name='Moment',
            output_name='moment',
            value_kind=DispatchValueKind.DATETIME,
            required=False,
        ),
        column(
            source_name='CurrentTime',
            output_name='current_time',
            value_kind=DispatchValueKind.DATETIME,
            required=False,
        ),
    ),
)
