name: atlanticus-e2e-full-local
services:
  pi-web-api:
    image: atlanticus-e2e-full-pi-web-api:local
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FILENAME: pi-web-api
    command: ["--run-once"]
    env_file:
      - ../processes/pi-web-api/.env
    environment:
      VOLUMEN_PATH: /app/volume
    volumes:
      - runtime:/app/volume
    cpus: 0.5
    mem_limit: 1g
  notpii:
    image: atlanticus-e2e-full-notpii:local
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FILENAME: notpii
    command: ["--run-once"]
    env_file:
      - ../processes/notpii/.env
    environment:
      VOLUMEN_PATH: /app/volume
    volumes:
      - runtime:/app/volume
    cpus: 0.5
    mem_limit: 1g
  dispatch:
    image: atlanticus-e2e-full-dispatch:local
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FILENAME: dispatch
    command: ["--run-once"]
    env_file:
      - ../processes/dispatch/.env
    environment:
      VOLUMEN_PATH: /app/volume
    volumes:
      - runtime:/app/volume
    cpus: 0.5
    mem_limit: 1g
  blockgrade:
    image: atlanticus-e2e-full-blockgrade:local
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FILENAME: blockgrade
    command: ["--run-once"]
    env_file:
      - ../processes/blockgrade/.env
    environment:
      VOLUMEN_PATH: /app/volume
    volumes:
      - runtime:/app/volume
    cpus: 0.5
    mem_limit: 1g
  fabrica:
    image: atlanticus-e2e-full-fabrica:local
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FILENAME: fabrica
    command: ["--run-once"]
    env_file:
      - ../processes/fabrica/.env
    environment:
      VOLUMEN_PATH: /app/volume
    volumes:
      - runtime:/app/volume
    cpus: 0.5
    mem_limit: 1g
  remanentes:
    image: atlanticus-e2e-full-remanentes:local
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FILENAME: remanentes
    command: ["--run-once"]
    env_file:
      - ../processes/remanentes/.env
    environment:
      VOLUMEN_PATH: /app/volume
    volumes:
      - runtime:/app/volume
    cpus: 0.5
    mem_limit: 1g

volumes:
  runtime:
